export const MAIN_API = "http://noteration.metindogancelik.com:8080";
export const ALL_NOTES_API = `${MAIN_API}/notes/all`;
export const CREATE_NOTE_API = `${MAIN_API}/notes/add/`;
export const READ_NOTE_API = `${MAIN_API}/notes/`;
export const UPDATE_NOTE_API = `${MAIN_API}/notes/edit/`;
export const DELETE_NOTE_API = `${MAIN_API}/notes/delete/`;
export const SHARE_NOTE_API = `${MAIN_API}/notes/share/`
export const LOGIN_API = `${MAIN_API}/login`;
export const LOGOUT_API = `${MAIN_API}/logout?hashCode=`;
export const SIGNUP_API = `${MAIN_API}/signup`;
export const AUTH_API = `${MAIN_API}/auth`;
export const FORGOT_PASSWORD_API = `${MAIN_API}/forgot-password?email=`;
export const NEW_PASSWORD_API = `${MAIN_API}/new-password/`;
export const ACTIVATE_ACCOUNT_API = `${MAIN_API}/activate-account/`;
export const GET_FULL_NAME_API = `${MAIN_API}/getFullName/`;
